nginx:
    image: nginx
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    links:
    - tomcat

tomcat:
    image: tomcat:8
    volumes:
    - ./tomcat-config/server.xml:/usr/local/tomcat/conf/server.xml
    - ./ROOT:/usr/local/tomcat/webapps/
    - ./library.war:/usr/local/tomcat/webapps/ROOT.war
    - ./tomcat-config/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
    - ./tomcat-config/context.xml:/usr/local/tomcat/conf/context.xml
    ports:
    - 8080:8080
